version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm install  # Installs project dependencies

  pre_build:
    commands:
      - echo Running pre-build steps...

  build:
    commands:
      - echo Building the React app...
      - npm run build  # Builds the React app into the build directory

  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  base-directory: dist
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules//*'  # Cache node_modules for faster builds